### ISSUE TITLE
1.0.0 is not on pypi

### ISSUE THREAD

**Issue by koug44** [ashleysommer/sanic-plugin-toolkit#20]
Hello,

Last release available through PIP is 0.9.5
Is it purposefully ?

Damien

**Comment by ashleysommer** [comment]
Hi.
It is here: https://pypi.org/project/sanic-plugin-toolkit/
As part of the v1.0.0 release, the  package name changed.
Yes, I know that is a breaking change, and yes that is intentional.
v1.0.0 works only with Sanic v21.3 and above.
But v0.9.5 works only with Sanic versions upto 20.12.x.
